#
# Makefile.common: 
#

asc_cmd		= ~/tools/bin/asc
src_dir		= ../src
lib_dir		= ../../../../ArisiaComponents/Resource/Library

as_scripts	= empty-frame.as \
		  property-boolean.as \
		  property-number.as \
		  property-string.as \
		  property-array.as \
		  property-dictionary.as \
		  property-enum.as \
		  property-init.as \
		  property-func.as \
		  property-listner.as \
		  property-frame.as \
		  init-0.as \
		  listner-0.as

decl_scripts	= $(as_scripts:.as=.d.ts)
js_scripts	= $(as_scripts:.as=.js)
ts_scripts	= $(as_scripts:.as=.ts)

tsc	= npx tsc
tsc_opt	= -t ES2017 --lib "es2017" --declaration \
	  --declarationDir $(CURDIR)/types \
	  --typeRoots $(CURDIR)/types \
	  --alwaysStrict --strict --strictNullChecks --pretty

%.js: %.as
	$(asc_cmd) -c $< > $@

%.ts: %.as
	$(asc_cmd) -c -l TypeScript $< > $@

