#
# Makefile
#

all:
	(cd hello.jspkg && make)
	(cd icon.jspkg && make)
	(cd table-data-0.jspkg && make)

clean:
	(cd hello.jspkg && make clean)
	(cd icon.jspkg && make clean)
	(cd table-data-0.jspkg && make clean)

