#
# Makefile
#

include ../Makefile.inc

srcs	= Button.md4 \
	  Box.md4 \
	  Collection.md4 \
	  Image.md4 \
	  Label.md4 \
	  TableData.md4
dsts	= $(srcs:.md4=.md)

all: $(dsts)

clean:
	rm -f $(dsts)


